# PATH = './data/raw/Marco/Incidentes 1° Semana - Março.xlsx'

INCIDENTS_CONFIG = {
    "id": "INCIDENTS_CONFIG",
    "rename_columns": {
        "Title": "Descricao Incidente",
        "Open Time @Timezone": "Horario de Abertura",
        "Open Group": "Grupo de Abertura",
        "Resolved Time @Timezone": "Horario de Resolucao",
        "Resolved Group": "Grupo de Resolucao",
    },
    "drop_columns": {
        "Unnamed: 0",
        "No.",
        "Call Code Name",
        "CI Type",
        "CI Subtype",
        "Prio",
        "VW Impact",
        "Ticket Type",
        "Company",
        "Location",
        "Department",
        "Reported Time @Timezone",
        "CI Riskclass",
        "Knowledge Candidate",
        "Problem Candidate",
        "Major Incident",
        "External",
        "Update Time @Timezone",
        "Close Time @Timezone",
        "Unnamed: 9",
    },
}

REQUESTS_CONFIG = {
    "id": "REQUESTS_CONFIG",
    "rename_columns": {
        "Title": "Descricao Incidente",
        "Open Time\n(Timezone based)": "Horario de Abertura",
        "Open Group": "Grupo de Abertura",
        "Resolve Time\n(Timezone based)": "Horario de Resolucao",
        "Resolve Group": "Grupo de Resolucao",
        "Reported CI Name": "CI",
    },
    "drop_columns": {
        "No.",
        "Template ID",
        "Assignment Group",
        "Complexity",
        "Update Time\n(Timezone based)",
        "Update Group",
        "Close Group",
        "Reported CI ID",
        "CI Type",
        "CI Location",
        "CI Environment",
        "Affected CI Name",
        "Affected CI ID",
        "Knowledge Candidate CI ID",
        "Escalation Status",
        "Autoclose",
        "Autoclose by",
        "Tag 1",
        "Tag 2",
        "Tag 3",
        "Tag 4",
        "Tag 5",
        "Tag 6",
        "Call Code",
        "Reported Time\n(Timezone based)",
        "Solution ID",
        "Opened by Interface",
        "Interface Takeover Time (Timezone based)",
        "External",
        "Reference ID",
        "Reported by Location",
        "Reported by Department",
    },
}

KEYWORDS = {
    "Armazenamento/Disco": [
        "filesystem",
        "disk g:",
        "disk c:",
        "space usage high",
        "low free space",
        "no available space",
        "disk used percentage",
        "volume usage",
        "partition full",
        "espaço usado",
    ],
    "Memória RAM": [
        "memory utilization",
        "low memory",
        "vmem",
        "swap usage",
        "swap",
        "physical memory",
        "insufficient memory",
    ],
    "CPU/Processamento": [
        "processor usage",
        "high cpu utilization",
        "load average",
        "cpu load",
        "performance | cpu",
        "processor queue length",
    ],
    "Banco de Dados - SQL Server": [
        "mssql",
        "sql server",
        "ad hoc queries",
        "transaction log",
        "sql agent",
        "database consistency",
        "deadlock",
        "sql browser",
    ],
    "Banco de Dados - Oracle": [
        "oracle",
        "ora-",
        "tns listener",
        "archive log",
        "db instance",
        "tablespace",
        "oracle cluster",
    ],
    "Rede/Conectividade": [
        "agent zabbix unavailable",
        "icmp ping",
        "packet loss",
        "network interface",
        "port unreachable",
        "latency high",
    ],
    "SAP": [
        "sap logon",
        "sapgui",
        "sap instance",
        "abap dump",
        "rfc connection",
        "sap database",
    ],
    "Indisponibilidade/Serviço": [
        "system was rebooted",
        "service down",
        "instance down",
        "not reachable",
        "process is not running",
        "uptime",
        "zabbix agent",
    ],
    "Backup/Jobs": ["netbackup", "job failed", "backup catalog", "maintenance task"],
}

MONTH_MAP = {
    1: "Janeiro",
    2: "Fevereiro",
    3: "Março",
    4: "Abril",
    5: "Maio",
    6: "Junho",
    7: "Julho",
    8: "Agosto",
    9: "Setembro",
    10: "Outubro",
    11: "Novembro",
    12: "Dezembro",
}

MONTHS_ORDER = [
    "Janeiro",
    "Fevereiro",
    "Março",
    "Abril",
    "Maio",
    "Junho",
    "Julho",
    "Agosto",
    "Setembro",
    "Outubro",
    "Novembro",
    "Dezembro",
]

FONT_STYLE = dict(size=16, color="black")
TITLE_STYLE = dict(size=20, color="black", weight="bold")
